sudo: required

language: python

python:
    - "2.7"

services:  
    - docker

install:
    - pip install -r requirements.txt

env:  
    global:
        - DOCKER_COMPOSE_VERSION=1.17.0

before_install:  
    # reinstall docker-compose at specific version
    - sudo rm -f /usr/local/bin/docker-compose
    - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
    - chmod +x docker-compose
    - sudo mv docker-compose /usr/local/bin

before_script:
    - pytest --version
    - docker version
    - docker-compose version

script:  
    # ensure build works
    - docker-compose up -d --build
    - docker ps # debug
    
    # run python tests
    - pytest tests
