FROM ubuntu:latest
RUN apt-get update -y

# Install python
RUN apt-get install -y python-pip python-dev build-essential

COPY . /app
WORKDIR /app

RUN pip install -r requirements.txt
EXPOSE 5000
CMD ["python", "matcha/app.py"]
