FROM ubuntu:latest
RUN apt-get update -y

# Install node
RUN apt-get install -y nodejs npm curl sudo

# Get latest Node 6.x
RUN curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
RUN sudo apt-get install -y nodejs

COPY ./react /js
WORKDIR /js

# Install necessary deps
RUN npm install -g yarn
RUN yarn install
EXPOSE 3000
#RUN yarn build
#CMD ["yarn", "start"]
CMD ["yarn", "dev"]
