version: '3'
services:
    flask:
        build:
          context: .
          dockerfile: Dockerfile.flask
        ports:
        - "5000:5000"
        volumes:
        - .:/code
        links:
        - db
        depends_on:
        - db
        container_name: matcha_flask
        environment:
        - DEV=1  # pass DEV environment variable to container
    web:
        build:
          context: .
          dockerfile: Dockerfile.react
        ports:
        - "3000:3000"
        volumes:
        - .:/code
        depends_on:
        - flask
        - db
        container_name: matcha_react
    db:
        image: mongo:3.4.10
        ports:
        - "27017:27017"
        container_name: matcha_mongo
        environment:
        - MONGO_INITDB_ROOT_USERNAME=matcha
        - MONGO_INITDB_ROOT_PASSWORD=letmein
        - MONGO_INITDB_DATABASE=matcha2
