version: '2'
services:
    flask:
        build:
          context: .
          dockerfile: Dockerfile.flask
        ports:
        - "5000:5000"
        volumes:
        - .:/code
    web:
        build:
          context: .
          dockerfile: Dockerfile.react
        ports:
        - "3000:3000"
        volumes:
        - .:/code
        links:
        - mongodb
    mongodb:
        image: mongo:3.4.10
        ports:
        - "27017:27017"
        container_name: mongodb_container
